# Generated by Django 4.1.3 on 2022-11-30 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_demo', '0004_remove_userinfo_data_alter_userinfo_age'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ROle',
        ),
    ]
