# Generated by Django 4.1.3 on 2022-12-03 03:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_demo', '0005_delete_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='goods_information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Goods_name', models.CharField(max_length=20)),
                ('User_id', models.BigIntegerField()),
                ('Peice', models.FloatField()),
                ('Label_id', models.BigIntegerField()),
                ('Decription', models.FloatField(max_length=100)),
                ('State', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='label',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='shopping_cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('User_id', models.BigIntegerField()),
                ('Goods_id', models.BigIntegerField()),
                ('State', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Buyer_id', models.BigIntegerField()),
                ('Seller_id', models.BigIntegerField()),
                ('Start_time', models.DateTimeField(auto_now=True)),
                ('End_time', models.DateTimeField(auto_now=True)),
                ('if_success', models.CharField(max_length=1)),
                ('Buyer_offer', models.FloatField()),
                ('Seller_offer', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='user_information',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('gender', models.CharField(max_length=1)),
                ('Telephone', models.CharField(max_length=11)),
                ('Registration_time', models.DateTimeField(auto_now=True)),
                ('QQ_number', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='user_password',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=20)),
            ],
        ),
        migrations.DeleteModel(
            name='Department',
        ),
        migrations.DeleteModel(
            name='UserInfo',
        ),
    ]
