11# Generated by Django 4.1.3 on 2022-12-03 03:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_demo', '0006_goods_information_label_shopping_cart_transaction_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goods_information',
            name='Decription',
            field=models.CharField(max_length=100),
        ),
    ]
