# Generated by Django 4.1.3 on 2022-12-30 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_demo', '0007_alter_goods_information_decription'),
    ]

    operations = [
        # migrations.AddField(
        #     model_name='transaction',
        #     name='Goods_id',
        #     field=models.BigIntegerField(default=0),
        #     preserve_default=False,
        # ),
        migrations.AlterField(
            model_name='goods_information',
            name='State',
            field=models.CharField(default='0', max_length=1),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='Start_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
