# Generated by Django 4.1.3 on 2023-01-06 16:12

import app_demo.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_demo', '0010_avatar_transaction_goods_id'),
    ]

    operations = [
        # migrations.CreateModel(
        #     name='Avatar',
        #     fields=[
        #         ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
        #         ('user', models.CharField(max_length=100)),
        #         ('photo', models.ImageField(default='avatar.jpg', storage=app_demo.storage.ImageStorage(), upload_to='img')),
        #     ],
        # ),
        # migrations.AddField(
        #     model_name='transaction',
        #     name='Goods_id',
        #     field=models.BigIntegerField(default=111),
        #     preserve_default=False,
        # ),
    ]
